default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TestMessenger_development

test:
  <<: *default
  database: TestMessenger_test

production:
  <<: *default
  database: TestMessenger_production
  username: TestMessenger
  password: <%= ENV['TESTMESSENGER_DATABASE_PASSWORD'] %>
